### ISSUE TITLE
Error opening the screen

### ISSUE THREAD

**Issue by ghost** [hubsif/kodi-tk_bbl#1]
First of all thanks a lot for creating that addon. However it worked only once and since than I am getting the following error

21:19:45 T:3059798016   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://universallivebbl-lh.akamaihd.net/i/p-2291_u-0_l-2291_hls_a-_c-DE_e-238_i-5655624220150221211944_k-1_q-_t-hdvideo/telekombasketball_5_1@89524/master.m3u8

Do you have any idea why this could happen? Please let me know if I can provide any log or try something.

**Comment by hubsif** [comment]
Hi tnfenster,

What platform are you running Kodi on? From some googling it looks like users encounter this error with different plugins, mostly when using RPi.
"error(22)" means HTTP error. This could be due to a server side or network issue, but it could also be a permissions error. Can you run the "curl" command with the url in the logs right after you tried to view a stream and post the output here (like "curl -v http://universallivebbl-lh.akamaihd.net/...")?

**Comment by ghost** [comment]
Hi hubsif,

I am indeed running on RPi, OpenELEC 4.2.1 to be exact. I just tried again and now it works, but as there is no game currently on it's just a replay. I'll try again with a live game.

**Comment by ghost** [comment]
Seems to be a permission problem? I get the following on a live game running curl:

```
raspi1:~ # curl -v  http://universallivebbl-lh.akamaihd.net/i/p-2291_u-0_l-2291_hls_a-_c-DE_e-243_i-2720314320150227204701_k-1_q-_t-hdvideo/telekombasketball_1_1@42855/master.m3u8
* Hostname was NOT found in DNS cache
*   Trying 23.14.93.46...
* Connected to universallivebbl-lh.akamaihd.net (23.14.93.46) port 80 (#0)
> GET /i/p-2291_u-0_l-2291_hls_a-_c-DE_e-243_i-2720314320150227204701_k-1_q-_t-hdvideo/telekombasketball_1_1@42855/master.m3u8 HTTP/1.1
> User-Agent: curl/7.37.1
> Host: universallivebbl-lh.akamaihd.net
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
* Server AkamaiGHost is not blacklisted
< Server: AkamaiGHost
< Mime-Version: 1.0
< Content-Type: text/html
< Content-Length: 512
< Expires: Fri, 27 Feb 2015 19:50:11 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Fri, 27 Feb 2015 19:50:11 GMT
< Connection: keep-alive
< Access-Control-Allow-Headers: *
< Access-Control-Expose-Headers: *
< Access-Control-Allow-Methods: GET, HEAD, OPTIONS
< Access-Control-Allow-Origin: *
< Set-Cookie: _alid_=uvNhLlh5+8sYW+gtSiOoBg==; path=/i/p-2291_u-0_l-2291_hls_a-_c-DE_e-243_i-2720314320150227204701_k-1_q-_t-hdvideo/telekombasketball_1_1@42855/; domain=universallivebbl-lh.akamaihd.net
< 
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;universallivebbl&#45;lh&#46;akamaihd&#46;net&#47;i&#47;p&#45;2291&#95;u&#45;0&#95;l&#45;2291&#95;hls&#95;a&#45;&#95;c&#45;DE&#95;e&#45;243&#95;i&#45;2720314320150227204701&#95;k&#45;1&#95;q&#45;&#95;t&#45;hdvideo&#47;telekombasketball&#95;1&#95;1&#64;42855&#47;master&#46;m3u8" on this server.<P>
Reference&#32;&#35;18&#46;2a5d0e17&#46;1425066611&#46;1270089
</BODY>
</HTML>
* Connection #0 to host universallivebbl-lh.akamaihd.net left intact
```

**Comment by ghost** [comment]
Just to confirm: Watching a recorded game still works on XBMC and I can access the live game with the same credentials on my iPad

Not sure if this helps but I also ran it on an additional OpenELEC-system, a cubox-i4pro and do have the same behaviour there. Recorded games work, live games produce error(22)

**Comment by xbmcmo** [comment]
At first i thank you. It works great. But on my raspi i can't watch the Eurocup Games. I don't know whats the problem and i think when the Playoffs start there is the same problem. Maybe you can fix it and do an update.

**Comment by xbmcmo** [comment]
Ps:Ther is no file wich i can watch

**Comment by hubsif** [comment]
Thanks for the feedback. Will look into this next weekend.

**Comment by hubsif** [comment]
I think I fixed the live streaming issue. Please try version 1.0.2 and let me know if it works for you.

**Comment by ghost** [comment]
Watching a live game right now. Once again, thanks a lot!
