### ISSUE TITLE
Version 1.1.3 Starten einer Liveübertragung

### ISSUE THREAD

**Issue by kedvsk** [hubsif/kodi-tk_bbl#12]
19:05:55 518221.937500 T:1283454016  NOTICE: -->Python Interpreter Initialized<--
19:05:56 518222.750000 T:1283454016  NOTICE: %H%H:%M:%S
19:06:08 518234.625000 T:1967149056   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tk_bbl/?scheduled_start=2016-12-21+18%3A45%3A00&mode=4&id=1000022]
19:06:08 518234.625000 T:1283454016  NOTICE: Thread BackgroundLoader start, auto delete: false
19:06:14 518241.125000 T:1210876992  NOTICE: Previous line repeats 1 times.
19:06:14 518241.125000 T:1210876992  NOTICE: Thread LanguageInvoker start, auto delete: false
19:06:14 518241.281250 T:1210876992  NOTICE: -->Python Interpreter Initialized<--
19:06:15 518242.468750 T:1283454016  NOTICE: Thread BackgroundLoader start, auto delete: false
19:06:22 518249.125000 T:1210876992  NOTICE: Previous line repeats 1 times.
19:06:22 518249.125000 T:1210876992  NOTICE: Thread LanguageInvoker start, auto delete: false
19:06:22 518249.250000 T:1210876992  NOTICE: -->Python Interpreter Initialized<--
19:06:23 518250.500000 T:1283454016  NOTICE: Thread BackgroundLoader start, auto delete: false
19:06:26 518252.875000 T:1210876992  NOTICE: Thread LanguageInvoker start, auto delete: false
19:06:26 518253.000000 T:1210876992  NOTICE: -->Python Interpreter Initialized<--
19:06:28 518254.875000 T:1258288192  NOTICE: Thread BackgroundLoader start, auto delete: false
19:06:33 518259.968750 T:1258288192  NOTICE: Previous line repeats 2 times.
19:06:33 518259.968750 T:1258288192  NOTICE: Thread LanguageInvoker start, auto delete: false
19:06:33 518260.125000 T:1258288192  NOTICE: -->Python Interpreter Initialized<--
19:06:34 518261.312500 T:1194099776  NOTICE: Thread BackgroundLoader start, auto delete: false
19:06:37 518264.062500 T:1258288192  NOTICE: Thread LanguageInvoker start, auto delete: false
19:06:37 518264.218750 T:1258288192  NOTICE: -->Python Interpreter Initialized<--
19:06:38 518265.031250 T:1258288192  NOTICE: %H%H:%M:%S
19:06:40 518267.312500 T:1258288192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tk_bbl/default.py", line 211, in <module>
                                                mobileUrl = re.search('mobileUrl: \"(.*?)\"', response).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
19:06:40 518267.531250 T:1967149056   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tk_bbl/?scheduled_start=2016-10-28+18%3A45%3A00&mode=4&id=1000097]
19:06:43 518270.093750 T:1258288192  NOTICE: Thread BackgroundLoader start, auto delete: false
19:06:45 518271.843750 T:1258288192  NOTICE: Thread LanguageInvoker start, auto delete: false
19:06:45 518271.968750 T:1258288192  NOTICE: -->Python Interpreter Initialized<--

**Comment by ghost** [comment]
2.2.0 Alpha works

kedvsk notifications@github.com schrieb am Fr., 28. Okt. 2016, 19:58:
