### ISSUE TITLE
Telekom Sport

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-tk_bbl#14]
Hallo, 
Die Telekom will ihre Sportangebote (BBL, DEL und 3. Liga) unter Telekomsport.de bündeln.

Kannst du dafür wieder ein Addon basteln. Danke

**Comment by ghost** [comment]
Wäre für ein Update auf Telekom Sport auch sehr dankbar.

Hab das Telekom Basketball Addon sehr gerne und problemlos genutzt!

**Comment by hubsif** [comment]
Ja, das hab ich jetzt auch durch das App-Update festgestellt...
Telekomsport.de scheint vom selben Provider und ähnlich aufgebaut zu sein wie BBL und DEL bisher. Mal sehen wann ich Zeit finde, das Addon dafür umzuschreiben.

**Comment by kakaiser** [comment]
super, danke - würde mich auch freuen.

Am 17. Juli 2017 um 17:44 schrieb hubsif <notifications@github.com>:

**Comment by MRLB** [comment]
Nice. Danke. Am Wochenende soll der 1. Spieltag der 3. Liga umsonst sein. Aber lass dich nicht stressen. BBL beginnt ja erst Ende September und DEL auch kaum vorher ;-)

**Comment by hubsif** [comment]
Hi,

Also ich hab mal ein neues Addon zusammengebastelt: [kodi-telekomsport](https://github.com/hubsif/kodi-telekomsport/releases)

Die Menüstruktur ist vom Server übernommen, da gibt es diesmal leider wenig Möglichkeit was dran zu ändern
Viel Spaß damit! Gebt Bescheid, wenn was nicht gefällt oder funktioniert.

**Comment by ghost** [comment]
Vielen Dank.

Werd ich mir gleich mal draufspielen.

**Comment by MRLB** [comment]
Danke. Werde es am Wochenende testen.

**Comment by kakaiser** [comment]
Auf Android und Libreelec läuft es soweit. Lediglich die Darstellung  der
Überschriften auf zwei Zeilen ist etwas zu eng.
Der Login ist auch noch nicht aktiv.

Gruß Karsten

Am 26.07.2017 22:31 schrieb "MRLB" <notifications@github.com>:

**Comment by hubsif** [comment]
> Lediglich die Darstellung der Überschriften auf zwei Zeilen ist etwas zu eng.

Hm, ich hatte es nur mit dem neuen Standardtheme (Estuary) getestet, da sieht es sehr gut aus. Aber beim vorherigen Confluence sieht es wirklich nicht so schön aus.

Welches Theme verwendest du? Vielleicht fällt mir noch ne bessere Lösung ein ...

**Comment by ghost** [comment]
Habe gerade mal meinen raspi auf den neuesten Stand gebracht und auch Kodi auf 17.3.

**Comment by ghost** [comment]
...Sorry da hab ich zu früh auf "Comment" geklickt :)

Was ich sagen wollte: Bei Kodi 17.3. sieht das mit den zwei Zeilen gut aus!

Freu mich auf die neue Saison.

**Comment by kakaiser** [comment]
Ich bin wegen WAF ... trotz aktueller Kodi Version noch auf auf dem
Confluence Skin. Auf Estuary ist der zeilenabstand besser ubd fubktionert.

Bei der DEL fehlt der Playoff Viertelfinale - Ordnername

Grüsse Karsten

Am 28. Juli 2017 um 01:10 schrieb Eckbert42 <notifications@github.com>:

**Comment by MRLB** [comment]
Danke. Es wird dann auch die Sky Bundesliga-Konferenz am Samstag und die Champions League-Konferenzen am Di/Mi via telekomsport geben. Dazu noch alle HBL-Spiele von Sky übernommen.

**Comment by MRLB** [comment]
@hubsif Kannst du noch den Login mit einbauen, damit man auch Pay-Videos schauen kann. Danke

**Comment by MRLB** [comment]
Bei der großen Auswahl demnächst (z. b. Sonntags mit 3. Liga/HBL/BBL und DEL zeitgleich) stellt sich für mich die Frage, ob es nicht auch möglich ist, ein 'Live' Menüpunkt zu kreieren, wo dann alle aktuell aktiven Streams erscheinen?

**Comment by hubsif** [comment]
@kakaiser 
> Ich bin wegen WAF ... trotz aktueller Kodi Version noch auf auf dem Confluence Skin.

😄 kann ich voll verstehen!

> Bei der DEL fehlt der Playoff Viertelfinale - Ordnername

Das liegt leider an den Daten, die vom Server geliefert werden. In der Smartphone App fehlt der Titel auch - nur fällt es da durch die graphische Darstellung nicht so auf.
Generell ist es schon wie bei den früheren Telekom Sportdingen am Anfang: Die Daten vom Server sind noch nicht so ganz "clean". Denke, das wird sich wieder ändern, wenn mehr Content kommt.

@MRLB 
> Danke. Es wird dann auch die Sky Bundesliga-Konferenz am Samstag und die Champions League-Konferenzen am Di/Mi via telekomsport geben. Dazu noch alle HBL-Spiele von Sky übernommen.

Das ist ja echt nicht schlecht! Muss ich natürlich mit einbauen!

> ob es nicht auch möglich ist, ein 'Live' Menüpunkt zu kreieren

Denke, das könnte mit dem Content vom Server möglich sein...
Allerdings hab ich heute erst festgestellt, dass die Live-Streams generell noch ein Problem haben. Werd mir das mal genauer ansehen.

Und vielen Dank für die Rückmeldungen!

**Comment by MRLB** [comment]
Die Sky-Sachen sind nun im Addon auswählbar.

**Comment by MRLB** [comment]
Was mir auch grad bei der 3. Liga-Livevorschau auffällt: die Streams sind alle 2 Stunden zu früh gelistet.

**Comment by hubsif** [comment]
Danke für das Feedback. Werde ich mir alles ansehen. Ich will für's nächste Update aber auch die live-Streams fixen und das geht nur, während einer läuft. Und bisher hatte ich leider nicht genau zu diesen Terminen Zeit. Ich hoffe, das sieht dieses Wochenende anders aus.

**Comment by kakaiser** [comment]
Planst du eigentlich noch die Login Daten mit aufzunehmen?

Schau dir parallel mal  noch den thread an:
https://www.kodinerds.net/index.php/Thread/57586-PreRelease-Telekom-Sport/?pageNo=2

Gruß Karsten

Am 08.08.2017 10:39 schrieb "hubsif" <notifications@github.com>:

**Comment by MRLB** [comment]
Das kodinerds-Plugin greift meiner Meinung nach die Webseite ab. Die App-API sollte sicherer sein. Ich warte lieber auf deine Version :-)

**Comment by kakaiser** [comment]
Yep, funktioniert auch super. Und ist lange erprobt.

Am 12.08.2017 09:14 schrieb "MRLB" <notifications@github.com>:

**Comment by hubsif** [comment]
So, hab gerade eine neue Version hochgeladen. Livestreams und Sky funktionieren bei mir grundsätzlich. Allerdings habe ich etwas mit der Struktur der API zu kämpfen, da diese nicht ganz konsistent ist, weshalb manche Sachen noch nicht wirklich schön angezeigt werden. Werde die Menüstruktur dahingehend noch ändern, die gewünschten Livespiele auf der Hauptseite anzeigen und die Spiele voraussichtlich wie im BBL-Addon nach Datum gruppiert anzeigen.

Und wie immer: Feedback und Verbesserungsvorschläge sind willkommen!

**Comment by kakaiser** [comment]
Super, Danke - bin noch im Urlaub werde erst kommende Woche zum Testen
kommen.

Was kostet denn eigentlich das Sky Sport Kompakt extra? Hab mich noch nicht
wirklich drum gekümmert.

Danke für deine Zeit die du investierst.

Am 19.08.2017 14:22 schrieb "hubsif" <notifications@github.com>:

**Comment by MRLB** [comment]
@hubsif Danke, gleich mal testen.

**Comment by MRLB** [comment]
@kakaiser Sky Sport Extra (inkl. sämtlicher Telekom-Stream) kostet für Entertain-Kunden 10 Euro, für Handy/Festnetzkunden 15 €/Monat)

**Comment by MRLB** [comment]
Läuft 1a bis jetzt. Und pünktlich vor der Bundesliga fertig - Du bist Spitze. Danke :-)

**Comment by kakaiser** [comment]
Das mit der Zeit von der API scheint  noch nicht ganz zu stimmen - siehe
Anhang.

Unddie Titelüberschrift im Kodi zeigt an "Ohne Namen" aber das hast du
wahrscheinlich auch schon  gesehen

Gruß Karsten

Am 19.08.2017 15:19 schrieb "MRLB" <notifications@github.com>:

**Comment by MRLB** [comment]
Auch wenn ich es wohl nie brauchen werde. Wäre es noch möglich den fcb.tv-Stream vom 24/7-Kanal mit einzubauen. Hat aber keine Priorität. Danke

**Comment by hubsif** [comment]
Hab gerade eine neue Version hochgeladen, die soweit mal fertig sein sollte. Es sollten alle Anmerkungen beachtet sein.
@MRLB Es gibt jetzt auch auf der Hauptseite einen Menüpunkt für Livespiele, falls gerade welche laufen.

Viel Spaß damit!

**Comment by MRLB** [comment]
Danke :-)

**Comment by MRLB** [comment]
Auf dem FireTV bekomme ich immer wieder ein paar Fehlermeldungen:

`18:14:24.307 T:1427068096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

                                            Error Type: <type 'exceptions.IOError'>

                                            Error Contents: [Errno socket error] ('The read operation timed out',)

                                            Traceback (most recent call last):

                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.telekomsport/default.py", line 256, in <module>

                                                locals()['get' + mode]()

                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.telekomsport/default.py", line 184, in getevent

                                                response = urllib.urlopen("https://www.telekomsport.de/api/v1" + args['event']).read()

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib.py", line 87, in urlopen

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib.py", line 213, in open

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib.py", line 444, in open_https

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 1211, in getreply

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 1136, in getresponse

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 453, in begin

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/httplib.py", line 409, in _read_status

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/socket.py", line 480, in readline

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/ssl.py", line 756, in recv

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/ssl.py", line 643, in read

                                            IOError: [Errno socket error] ('The read operation timed out',)

                                            -->End of Python script error report<--`

Beim spätestens dritten Mal ungefähr funktioniert es, was irgendwie komisch ist.

**Comment by hubsif** [comment]
Hm, eigentlich sagt der Fehler, dass es ein Problem zwischen der Verbindung deines Gerätes und dem telekomsport.de-Server gibt. Das kann natürlich an vielem liegen - hoffentlich an einem Problem mit dem Telekom Server. Besteht das Problem immer noch/dauerhaft?

Ach, und mach für sowas jetzt besser ein Issue auf [kodi-telekomsport](https://github.com/hubsif/kodi-telekomsport) auf ;)

**Comment by MRLB** [comment]
Am Samstag (bei der Vorgänger-Version), gab's das Problem nicht. Heute hab ich fcb.tv getestet, da kam es. Hat auch alles sehr langsam geladen. Mal beobachten und dann falls es weiter auftaucht bei telekomsport ein issue aufmachen. Erst bei dritten Ladeversuch ging fcb.tv auf.

**Comment by kakaiser** [comment]
Ist mir der Umstellung von Telekomsport auf Magentasport ein Update geplant?

Am Di., 22. Aug. 2017 um 21:44 Uhr schrieb MRLB <notifications@github.com>:

**Comment by hubsif** [comment]
Hallo kakaiser,

Na du bist aber schnell informiert. Musste erst mal testen und googlen... ;)

Dieses Addon hier ist ja sowieso schon lange überholt von [kodi-telekomsport](https://github.com/hubsif/kodi-telekomsport). Auch da bin ich aber schon total hintendran mit Anpassungen/Verbesserungen.
Je nachdem wieviel Veränderungen mit dem Update auf "Magentasport" kommen bzw. kamen (von [telekom.com](https://www.telekom.com/de/konzern/details/aus-telekom-sport-wird-magentasport-557882): _Mit dem neuen Namen kommen eine verbesserte Bedieneroberfläche und ein moderneres Design._), werde ich versuchen, das Addon anzupassen. Aber momentan sieht es aus, als hätte sich v.a. der Namen geändert, das Addon selbst funktioniert wohl soweit noch.
Alles weitere dann im [Telekomsport Addon](https://github.com/hubsif/kodi-telekomsport).
