### ISSUE TITLE
Nur Zusammenfassungen werden angezeigt

### ISSUE THREAD

**Issue by ghost** [hubsif/kodi-tk_bbl#4]
Hallo,

für vergangene Spiele werden mittlerweile nur noch die Zusammenfassungen angezeigt. Perfekt wäre es, wenn wieder die komplette Wiederholung und zusätzlich auch die Zusammenfassung angezeigt werden könnte

**Comment by hubsif** [comment]
Hm, das liegt wohl daran, dass das serverseitig umgestellt wurde. In der Smartphone App werden zu den Spieltagen jetzt auch nur noch die Zusammenfassungen angezeigt. Wählt man jedoch eine aus, hat man die Wiederholungen als "Related Videos", sie sind also generell noch verfügbar.

Werde das bei Gelegenheit mal genauer analysieren und sehen, wie ich das am Besten integriere...

**Comment by hubsif** [comment]
Also ich hab mir das mal angesehen und es geht wohl nur mit einer "Bastellösung". Allerdings möchte ich noch die Playoffs abwarten um sicherzugehen, dass diese Lösung dann auch dafür und somit allgemein verwendbar ist.

**Comment by ghost** [comment]
Ok, sehr verständlich. Für mich persönlich wäre es am geschicktesten, wenn in der Liste die Zusammenfassungen und die vollen Wiederholungen direkt zugreifbar wären, sind ja trotzdem nur 18 Einträge maximal. Aber letzten Endes egal, auch irgendwie über das Kontextmenu oder sonstwas fände ich super, Hauptsache irgendwie zugreifbar

Danke vorab

**Comment by hubsif** [comment]
So, mit Version 1.1.0 werden jetzt alle Arten von verfügbaren Videos zu einem Spiel in einem Unterordner angezeigt, d.h. man kann jetzt auch die Interviews usw. ansehen.

**Comment by ghost** [comment]
Perfekt, vielen Dank! Kann ich mich in irgendeiner Form auch monetär oder sonstwie bedanken?

**Comment by hubsif** [comment]
Sehr nett, aber ich habe mich schon so viel durch Projekte der Open Source Community bereichtert, dass ich froh bin nun selbst mal etwas beitragen zu können. Zu wissen, dass meine Arbeit Anderen nutzt, gibt mir das Gefühl auch wirklich etwas beigesteuert zu haben und ist mir somit Dank genug! :wink:
