### ISSUE TITLE
FireTV

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-tk_bbl#5]
I get this error message when I try to start the addon on Amazon Fire TV:

14:00:18 T:1671165032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: decode() argument 1 must be string, not None
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tk_bbl/default.py", line 29, in <module>
                                                _addon_path    = _addon.getAddonInfo('path').decode(sys.getfilesystemencoding())
                                            TypeError: decode() argument 1 must be string, not None
                                            -->End of Python script error report<--
14:00:18 T:1540067704   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.tk_bbl/
14:00:18 T:1540067704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tk_bbl/) failed

**Comment by hubsif** [comment]
Thank you for reporting!
Please try again with version 1.1.1, which should have fixed this issue.
