### ISSUE TITLE
Playback of live games from main menu doesn't work

### ISSUE THREAD

**Issue by localhosthack0r** [hubsif/kodi-tk_bbl#6]
First of all, thank you very much for your work on this great addon, for all of us basketball enthusiast out there! :-)

Live games are correctly shown in main menu, but playback doesn't work from there.
Here a log snippet:

16:23:17 T:140398886557440  NOTICE: Thread LanguageInvoker start, auto delete: false
16:23:17 T:140398886557440  NOTICE: -->Python Interpreter Initialized<--
16:23:17 T:140398886557440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('type',)
                                            Traceback (most recent call last):
                                              File "/var/lib/vdr/.xbmc/addons/plugin.video.tk_bbl/default.py", line 150, in <module>
                                                li = xbmcgui.ListItem(args['type'][0], iconImage=args['iconImage'][0], thumbnailImage=args['thumbnailImage'][0])
                                            KeyError: ('type',)
                                            -->End of Python script error report<--
16:23:17 T:140399718864768   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tk_bbl/?scheduled_start=2015-11-08+14%3A45%3A00&mode=3&id=2256]
16:23:28 T:140398886557440  NOTICE: Thread BackgroundLoader start, auto delete: false

If this game is choosen from Hauptrunde --> Spieltag 7 it's working fine.

**Comment by hubsif** [comment]
Hi localhosthack0r,
your comment got lost somehow...
Display of live games had been broken for a while, but should be working again with release v1.1.2.
