### ISSUE TITLE
Vielen Dank für die tolle app

### ISSUE THREAD

**Issue by wepe53** [hubsif/kodi-tk_bbl#7]
Hi,
vielen vielen Dank für diese tolle app. Als Basketball-Fan und neuer User eines Raspberry Kodi Media Centers kann ich nun im Wohnzimmer ohne meinen Laptop Basketball schauen - super!
Da ich nicht wusste, wie ich meinen Dank ausdrücken kann (ich hätte auch gerne etwas gespendet), habe ich der Einfachheit halber einen Account bei Github eröffnet und ein Pseudo-Issue eröffnet.
Sollte mir an der app etwas auffallen bzw. ich Fehler feststellen, dann melde ich mich wieder.

:-) W.P.

**Comment by hubsif** [comment]
Hm, ist schon ne ganze Weile her dein Kommentar, ging irgendwie verloren...

Vielen Dank jedenfalls, freut mich, wenn ich jemanden glücklich machen konnte!
